print("I like cookies")
print("Hello, I'm here for git practice. - Local")
print("Sometimes I think about how dogs are better than cats")
print("Hello, I'm here for git practice - Remote")
print("Sometimes I realize mr klins HATES US!!!!")
print("Added during merge")
print("Remote end")
print("working from dev branch")
